[[Gnuplot]]
arch = "aarch64"
git-tree-sha1 = "4e6ae208a0545bb8991f0469a24d0fa34938bc6a"
os = "macos"

    [[Gnuplot.download]]
    sha256 = "4c4ad740e37e365fe4c83bc55db66fd92e2e16da3e43259c3d5eb3af055d162f"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.aarch64-apple-darwin.tar.gz"
[[Gnuplot]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7787c8b1ae9cef665b54cb977efa32158e3f67d8"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "c841014f10dd4d39d665ef1daf03d840991d12fbd1c7279a3d4c4070ea71e70a"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.aarch64-linux-gnu-cxx11.tar.gz"
[[Gnuplot]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a251b7249ce7d4530fdd33946b6c282f676481c6"
libc = "musl"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "869565e218b92cb472d31c5798818806b113658a4dde16d7e1369bee6f53fd57"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.aarch64-linux-musl-cxx11.tar.gz"
[[Gnuplot]]
arch = "aarch64"
git-tree-sha1 = "11adcda4d5a5ab35d375a2c7fff699746fe19eba"
os = "freebsd"

    [[Gnuplot.download]]
    sha256 = "910425c7408f2a5f80408c0854db0b4287541430de9f1d1f43b7f2467d170b7e"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.aarch64-unknown-freebsd.tar.gz"
[[Gnuplot]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5543b8f914f37cb96329f28fcb3e6399196b05b5"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "57fc7bfffb267dde59158b700d9376c7d12cd6f44aa6ef50e3e80aca1570958d"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Gnuplot]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "012aa59c6dd0f9fb726f5eb18f76edc9c0746f8f"
libc = "musl"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "ef414b8c27630d8ccba678dfedc063ba75d777e3ebf9d27e1443d8a39c407837"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Gnuplot]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35577a8e9203bc5801282670ccefa0c8783c5ba0"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "caf51c421096a7d17f5e891a7f9c8785173ec9a73cd3772a425645d123616e3b"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Gnuplot]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a584a0bd610aa2122db91fdf994cb55450826b86"
libc = "musl"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "d4c3e0e0b288cff77af17e13fae1292b6ed846fac80f0150e69f5cd5196b3061"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Gnuplot]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "349ac710fad20dafac41295a102c284c08613c53"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "6eca8de1971f4139c7e406d07ba68ab368f940e619e60ab3a6671a399d3397c8"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.i686-linux-gnu-cxx11.tar.gz"
[[Gnuplot]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fcb43ccdf353cb18d75f298e50f514152670c9c0"
libc = "musl"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "e646e9b0ab07d89b45092b9f7f05865495037c3be41f2a93602f24806cf17e35"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.i686-linux-musl-cxx11.tar.gz"
[[Gnuplot]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36004f5fd87ebf78fab1b81ed03dbdce90d7d39c"
os = "windows"

    [[Gnuplot.download]]
    sha256 = "6310376f77a0a54b16a706356cb3132552fe436076eb091fbb9f613a60848fb1"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.i686-w64-mingw32-cxx11.tar.gz"
[[Gnuplot]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db463260dc7e5925ced30c56d44427cdeaf2eb74"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "3989cacdd763d0d3cf68c1b9820e9f4c5a760715e921eedb8be6776d9b0f77e1"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Gnuplot]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81e21f7b5f156f1d46808449528bfb27526a7513"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "04a888cd545aac02cb8f9022d32741ea5866dfda05f2d837dc20a88472b745f5"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.riscv64-linux-gnu-cxx11.tar.gz"
[[Gnuplot]]
arch = "x86_64"
git-tree-sha1 = "fc461a27cbd99d2d962053e6427560cba7986abf"
os = "macos"

    [[Gnuplot.download]]
    sha256 = "d6d1b635175dfa34d3e8f61ae470bafa5bb2f94bae9b12c1031e28a3a26de1b7"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.x86_64-apple-darwin.tar.gz"
[[Gnuplot]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b73cddb20a95487a7f57776f409a1cd9a90b5b0a"
libc = "glibc"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "0cf3fdef5b2f60d311aeff2387bc20ae088c883d012bc8dd7be9f785d70250e6"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.x86_64-linux-gnu-cxx11.tar.gz"
[[Gnuplot]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cc82ca46a12fcb3284ac0cef641c7fb79b04304"
libc = "musl"
os = "linux"

    [[Gnuplot.download]]
    sha256 = "75239efe30061d97ae11963f9f38e08ed12fa95950bd1f5cef540b3e06dbb46e"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.x86_64-linux-musl-cxx11.tar.gz"
[[Gnuplot]]
arch = "x86_64"
git-tree-sha1 = "7dd3f1ababa2c688264b46bc42440d1f8edaf216"
os = "freebsd"

    [[Gnuplot.download]]
    sha256 = "5a1fb985eee8e028addc071c900c274a32296fecc6a40954d6665c4d3b75d0bc"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.x86_64-unknown-freebsd.tar.gz"
[[Gnuplot]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77dc1245a5a0a42fb966744bae894010055b179c"
os = "windows"

    [[Gnuplot.download]]
    sha256 = "73f4ff8cc1e8c3e12fb7c7c8d890d420fccc20df03bdc48a36274ec9dae43abb"
    url = "https://github.com/JuliaBinaryWrappers/Gnuplot_jll.jl/releases/download/Gnuplot-v60.0.4000+0/Gnuplot.v60.0.4000.x86_64-w64-mingw32-cxx11.tar.gz"
